s="""{
	"Algeria": "Africa",
	"Angola": "Africa",
	"Benin": "Africa",
	"Botswana": "Africa",
	"Burkina Faso": "Africa",
	"Burundi": "Africa",
	"Cabo Verde/Cape Verde": "Africa",
	"Cameroon": "Africa",
	"Central African Republic": "Africa",
	"Chad": "Africa",
	"Comoros": "Africa",
	"Congo/Republic of the Congo": "Africa",
	"Democratic Republic of the Congo": "Africa",
	"Djibouti": "Africa",
	"Egypt": "Africa",
	"Equatorial Guinea": "Africa",
	"Eritrea": "Africa",
	"Eswatini": "Africa",
	"Ethiopia": "Africa",
	"Gabon": "Africa",
	"Gambia, The": "Africa",
	"Ghana": "Africa",
	"Guinea": "Africa",
	"Guinea-Bissau": "Africa",
	"Ivory Coast/Republic of Côte d'Ivoire": "Africa",
	"Kenya": "Africa",
	"Lesotho": "Africa",
	"Liberia": "Africa",
	"Libya": "Africa",
	"Madagascar": "Africa",
	"Malawi": "Africa",
	"Mali": "Africa",
	"Mauritania": "Africa",
	"Mauritius": "Africa",
	"Morocco": "Africa",
	"Mozambique": "Africa",
	"Namibia": "Africa",
	"Niger": "Africa",
	"Nigeria": "Africa",
	"Rwanda": "Africa",
	"Sao Tome and Principe": "Africa",
	"Senegal": "Africa",
	"Seychelles": "Africa",
	"Sierra Leone": "Africa",
	"Somalia": "Africa",
	"South Africa": "Africa",
	"South Sudan": "Africa",
	"Sudan": "Africa",
	"Tanzania": "Africa",
	"Togo": "Africa",
	"Tunisia": "Africa",
	"Uganda": "Africa",
	"Zambia": "Africa",
	"Zimbabwe": "Africa",
	"Canary Islands": "Africa",
	"Ceuta": "Africa",
	"French Southern and Antarctic Lands": "Africa",
	"Madeira": "Africa",
	"Mayotte": "Africa",
	"Melilla (Spain)": "Africa",
	"Pelagie Islands (Italy)": "Africa",
	"Plazas de Soberania (Spain)": "Africa",
	"Reunion (France)": "Africa",
	"Saint Helena, Ascension and Tristan da Cunha (UK)": "Africa",
	"Socotra Archipelago (Yemen)": "Africa",
	"Afghanistan": "Asia",
	"Armenia (transcontinental - generally considered Asian)": "Asia",
	"Azerbaijan (transcontinental - generally considered Asian)": "Asia",
	"Bahrain": "Asia",
	"Bangladesh": "Asia",
	"Bhutan": "Asia",
	"British Indian Ocean Territory (UK territory)": "Asia",
	"Brunei": "Asia",
	"Cambodia": "Asia",
	"China": "Asia",
	"Cyprus (transcontinental - generally considered European)": "Asia",
	"Egypt (transcontinental - generally considered African)": "Asia",
	"Georgia (transcontinental - generally considered Asian)": "Asia",
	"Hong Kong (China - Special Administrative Region)": "Asia",
	"India": "Asia",
	"Indonesia": "Asia",
	"Iran": "Asia",
	"Iraq": "Asia",
	"Israel (U.N. member, though partially unrecognized)": "Asia",
	"Japan": "Asia",
	"Jordan": "Asia",
	"Kazakhstan (transcontinental - generally considered Asian)": "Asia",
	"Kuwait": "Asia",
	"Kyrgyzstan": "Asia",
	"Laos": "Asia",
	"Lebanon": "Asia",
	"Macau (China - Special Administrative Region)": "Asia",
	"Malaysia": "Asia",
	"Maldives": "Asia",
	"Mongolia": "Asia",
	"Myanmar (formerly Burma)": "Asia",
	"Nepal": "Asia",
	"North Korea (Democratic People's Republic of Korea)": "Asia",
	"Oman": "Asia",
	"Pakistan": "Asia",
	"Palestine (limited recognition)": "Asia",
	"Philippines": "Asia",
	"Qatar": "Asia",
	"Saudi Arabia": "Asia",
	"Singapore": "Asia",
	"South Korea (Republic of Korea)": "Asia",
	"Sri Lanka": "Asia",
	"Syria": "Asia",
	"Taiwan (limited recognition - claimed by China)": "Asia",
	"Tajikistan": "Asia",
	"Thailand": "Asia",
	"Timor-Leste/East Timor": "Asia",
	"Turkmenistan": "Asia",
	"United Arab Emirates": "Asia",
	"Uzbekistan": "Asia",
	"Vietnam": "Asia",
	"Yemen": "Asia",
	"Albania": "Europe",
	"Andorra": "Europe",
	"Austria": "Europe",
	"Belarus": "Europe",
	"Belgium": "Europe",
	"Bosnia and Herzegovina": "Europe",
	"Bulgaria": "Europe",
	"Croatia": "Europe",
	"Cyprus (generally considered European)": "Europe",
	"Czechia/Czech Republic": "Europe",
	"Denmark": "Europe",
	"Estonia": "Europe",
	"Finland": "Europe",
	"France": "Europe",
	"Germany": "Europe",
	"Greece": "Europe",
	"Hungary": "Europe",
	"Iceland": "Europe",
	"Ireland": "Europe",
	"Italy": "Europe",
	"Latvia": "Europe",
	"Liechtenstein": "Europe",
	"Lithuania": "Europe",
	"Luxembourg": "Europe",
	"Malta": "Europe",
	"Moldova": "Europe",
	"Monaco": "Europe",
	"Montenegro": "Europe",
	"Netherlands": "Europe",
	"North Macedonia": "Europe",
	"Norway": "Europe",
	"Poland": "Europe",
	"Portugal": "Europe",
	"Romania": "Europe",
	"Russia (transcontinental - generally considered European)": "Europe",
	"San Marino": "Europe",
	"Serbia": "Europe",
	"Slovakia": "Europe",
	"Slovenia": "Europe",
	"Spain": "Europe",
	"Sweden": "Europe",
	"Switzerland": "Europe",
	"Turkey (transcontinental - generally considered European)": "Europe",
	"Ukraine": "Europe",
	"United Kingdom": "Europe",
	"Vatican City (Holy See)": "Europe",
	"Åland (Finland)": "Europe",
	"Channel Islands (UK)": "Europe",
	"Faroe Islands (Denmark)": "Europe",
	"Gibraltar (UK)": "Europe",
	"Guernsey (UK - crown dependency)": "Europe",
	"Isle of Man (UK - crown dependency)": "Europe",
	"Jersey (UK - crown dependency)": "Europe",
	"Kosovo (partially recognized, claimed by Serbia)": "Europe",
	"Northern Cyprus (not recognized, claimed by Cyprus)": "Europe",
	"Northern Ireland (UK)": "Europe",
	"Svalbard (Norway)": "Europe",
	"Greenland": "North America",
	"Canada": "North America",
	"United States of America": "North America",
	"Saint Pierre and Miquelon": "North America",
	"Antigua and Barbuda": "Central America and Caribbean",
	"Bahamas": "Central America and Caribbean",
	"Barbados": "Central America and Caribbean",
	"Belize": "Central America and Caribbean",
	"Costa Rica": "Central America and Caribbean",
	"Cuba": "Central America and Caribbean",
	"Dominica": "Central America and Caribbean",
	"Dominican Republic": "Central America and Caribbean",
	"El Salvador": "Central America and Caribbean",
	"Grenada": "Central America and Caribbean",
	"Guatemala": "Central America and Caribbean",
	"Haiti": "Central America and Caribbean",
	"Honduras": "Central America and Caribbean",
	"Jamaica": "Central America and Caribbean",
	"Mexico": "Central America and Caribbean",
	"Nicaragua": "Central America and Caribbean",
	"Panama": "Central America and Caribbean",
	"Saint Kitts and Nevis": "Central America and Caribbean",
	"Saint Lucia": "Central America and Caribbean",
	"Saint Vincent and the Grenadines": "Central America and Caribbean",
	"Trinidad and Tobago": "Central America and Caribbean",
	"Anguilla (UK)": "Central America and Caribbean",
	"Aruba (Netherlands)": "Central America and Caribbean",
	"Bermuda (UK)": "Central America and Caribbean",
	"Bonaire (Netherlands)": "Central America and Caribbean",
	"British Virgin Islands (UK)": "Central America and Caribbean",
	"Cayman Islands (UK)": "Central America and Caribbean",
	"Clipperton Island (France)": "Central America and Caribbean",
	"Curaçao (Netherlands)": "Central America and Caribbean",
	"Greenland (Denmark)": "Central America and Caribbean",
	"Guadeloupe (France)": "Central America and Caribbean",
	"Martinique (France)": "Central America and Caribbean",
	"Montserrat (UK)": "Central America and Caribbean",
	"Navassa Island (USA)": "Central America and Caribbean",
	"Puerto Rico (USA)": "Central America and Caribbean",
	"Saba (Netherlands)": "Central America and Caribbean",
	"Saint Barthélemy (France)": "Central America and Caribbean",
	"Saint Martin (France)": "Central America and Caribbean",
	"Saint Pierre and Miquelon (France)": "Central America and Caribbean",
	"Sint Eustatius (Netherlands)": "Central America and Caribbean",
	"Sint Maarten (Netherlands)": "Central America and Caribbean",
	"Turks and Caicos (UK)": "Central America and Caribbean",
	"US Virgin Islands (USA)": "Central America and Caribbean",
	"Australia": "Oceania",
	"Fiji": "Oceania",
	"Kiribati": "Oceania",
	"Marshall Islands": "Oceania",
	"Micronesia (The Federated States of)": "Oceania",
	"Nauru": "Oceania",
	"New Zealand": "Oceania",
	"Palau": "Oceania",
	"Papua New Guinea": "Oceania",
	"Samoa": "Oceania",
	"Solomon Islands": "Oceania",
	"Tonga": "Oceania",
	"Tuvalu": "Oceania",
	"Vanuatu": "Oceania",
	"American Samoa (US)": "Oceania",
	"Ashmore and Cartier Islands (Australia)": "Oceania",
	"Baker Island (US)": "Oceania",
	"Cook Islands (New Zealand)": "Oceania",
	"Coral Sea Islands (Australia)": "Oceania",
	"Easter Island (Chile)": "Oceania",
	"French Polynesia (France)": "Oceania",
	"Galapagos Islands (Ecuador)": "Oceania",
	"Guam (US)": "Oceania",
	"Howland Island (US)": "Oceania",
	"Jarvis Island (US)": "Oceania",
	"Johnston Atoll (US)": "Oceania",
	"Kingman Reef (US)": "Oceania",
	"Midway Atoll (US)": "Oceania",
	"New Caledonia (France)": "Oceania",
	"Niue (New Zealand)": "Oceania",
	"Norfolk Island (Australia)": "Oceania",
	"Northern Mariana Islands (US)": "Oceania",
	"Palmyra Atoll (US)": "Oceania",
	"Papua (Indonesia) (Not same as Papua New Guinea)": "Oceania",
	"Pitcairn Islands (UK)": "Oceania",
	"San Andrés and Providencia (Colombia)": "Oceania",
	"Tokelau (New Zealand)": "Oceania",
	"Wake Island (US)": "Oceania",
	"Wallis and Futuna (France)": "Oceania",
	"West Papua (Indonesia)": "Oceania",
	"Argentina": "South America",
	"Bolivia": "South America",
	"Brazil": "South America",
	"Chile": "South America",
	"Colombia": "South America",
	"Ecuador": "South America",
	"Guyana": "South America",
	"Paraguay": "South America",
	"Peru": "South America",
	"Suriname": "South America",
	"Uruguay": "South America",
	"Venezuela": "South America",
	"Bouvet Island (Norway)": "South America",
	"Falkland Islands (UK)": "South America",
	"French Guinea (France)": "South America",
	"Nueva Esparta (Venezuela)": "South America",
	"South Georgia and the South Sandwich Islands (UK)": "South America"
}"""









import re 
print(re.sub("[\(\[].*?[\)\]]", "", s).replace(" \"",'"').replace(" \"",'"').replace(" \"",'"').replace(" \"",'"').replace(" \"",'"').replace(" \"",'"').replace(" \"",'"').replace(" \"",'"').replace(" \"",'"').replace(" \"",'"').replace(" \"",'"').replace(" \"",'"').replace(" \"",'"').replace(" \"",'"').replace(" \"",'"').replace(" \"",'"').replace(" \"",'"').replace(" \"",'"').replace(" \"",'"').replace(" \"",'"').replace(" \"",'"').replace('":"','": "'))